Resources:
  MySqlStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://goh-cfn-bucket.s3-ap-southeast-1.amazonaws.com/MySQLv2.yaml"

  DynamoStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://goh-cfn-bucket.s3-ap-southeast-1.amazonaws.com/dynamodbv2.yaml"
  
  LambdaStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://goh-cfn-bucket.s3-ap-southeast-1.amazonaws.com/lambdaV3.yaml"
      
  NatGWStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://goh-cfn-bucket.s3-ap-southeast-1.amazonaws.com/natGW.yaml"

  CognitoStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://goh-cfn-bucket.s3-ap-southeast-1.amazonaws.com/cognito.yaml"      
  
  AppSyncStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://goh-cfn-bucket.s3-ap-southeast-1.amazonaws.com/AppSync.yaml"   