Resources:

  DynamoStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://github.com/thgoh/Assignment/blob/main/nested/dynamodbv2.yaml"
      
  SnsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: "https://github.com/thgoh/Assignment/blob/main/nested/dynamodbv2.yaml"
          